# dice-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dice-simulator-service
spec:
  selector:
    app: dice-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer